name: Master Branch Workflow

permissions:
  contents: write

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-test:
    name: Build and Test
    uses: ./.github/workflows/shared-build-test.yml
    with:
      dotnet-version: '9.0.x'

  semantic-versioning:
    name: Calculate and update new semantic version
    needs: [ build-and-test ]
    uses: ./.github/workflows/dotnet-semantic-version.yml
    with:
      version-file-path: './src/BookStore.Api/BookStore.Api.csproj'

  deploy:
    name: Deploy ${{ github.ref_name }} branch
    needs: [ semantic-versioning ]
    uses: ./.github/workflows/shared-deployment.yml
    with:
      webhook-url: ${{ vars.WEBHOOK_URL }}
      application-id: ${{ vars.APPLICATION_ID }}
      version: ${{ needs.semantic-versioning.outputs.new-version }}
      branch: ${{ github.ref_name }}
