name: Master Branch Pipeline

permissions:
  contents: write

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-test:
    name: Build solution and Test  
    uses: ./.github/workflows/shared-build-test.yml
    with:
      dotnet-version: '9.0.x'

  semantic-versioning:
    name: Generate New Version
    needs: [ build-and-test ]
    uses: ./.github/workflows/shared-dotnet-semantic-version.yml
    with:
      version-file-path: './src/BookStore.Api/BookStore.Api.csproj'

  # deploy:
    # name: Deploy to Target Environment
    # needs: [ semantic-versioning ]
    # uses: ./.github/workflows/shared-node-deployment.yml
    # with:
      #deployment-service-address: ${{ vars.DEPLOYMENT_SERVICE_ADDRESS }}
      #application-id: ${{ vars.APPLICATION_ID }}
      #version: ${{ needs.semantic-versioning.outputs.new-version }}
      #branch: ${{ github.ref_name }}