name: Master Branch Workflow

permissions:
  contents: write

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install project dependencies
        run: dotnet restore

      - name: Run build
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      - name: Extract current version from csproj
        id: get_version
        run: |
          VERSION=$(grep -oP '(?<=<Version>)(.*?)(?=</Version>)' src/BookStore.Api/BookStore.Api.csproj)
          if [ -z "$VERSION" ]; then
            echo "Error: Version tag not found in project file"
            exit 1
          fi
          echo "Current version: $VERSION"
          echo "CURRENT_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Calculate next version number
        id: bump_version
        run: |
          CURRENT_VERSION="${{ env.CURRENT_VERSION }}"
          MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
          MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
          PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)
          
          if git log -1 --pretty=%B | grep -q '\[major\]'; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
          elif git log -1 --pretty=%B | grep -q '\[minor\]'; then
            MINOR=$((MINOR + 1))
            PATCH=0
          else
            PATCH=$((PATCH + 1))
          fi

          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "New version: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Setup Git credentials
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git fetch origin master

      - name: Update version and push changes
        run: |
          sed -i "s/<Version>.*<\/Version>/<Version>${{ env.NEW_VERSION }}<\/Version>/" src/BookStore.Api/BookStore.Api.csproj
          git add src/BookStore.Api/BookStore.Api.csproj
          git commit -m "Bump version to ${{ env.NEW_VERSION }}"
          git pull --rebase origin master
          git push origin master

      - name: Create and push version tag
        run: |
          git tag -a "v${{ env.NEW_VERSION }}" -m "Release version ${{ env.NEW_VERSION }}"
          git push origin "v${{ env.NEW_VERSION }}"

      - name: Trigger deployment webhook
        if: success()
        run: |
          response=$(curl -w "\n%{http_code}" -X POST "${{ vars.WEBHOOK_URL }}/api/github" \
          -H "Content-Type: application/json" \
          -d '{
            "branch": "${{ github.ref_name }}",
            "appId": "${{ vars.APPLICATION_ID }}"
          }')
          status_code=$(echo "$response" | tail -n1)
          if [ "$status_code" -lt 200 ] || [ "$status_code" -ge 300 ]; then
            echo "Deployment webhook failed with status: $status_code"
            exit 1
          fi