name: Master Branch Workflow

permissions:
  contents: write

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-test:
    uses: ./.github/workflows/shared-build-test.yml
    with:
      dotnet-version: '9.0.x'

  determine-new-version:
    needs: build-and-test
    uses: ./.github/workflows/shared-version-management.yml
    with:
      project-path: './src/BookStore.Api/BookStore.Api.csproj'

  commit-version-and-tag:
    needs: determine-new-version
    uses: ./.github/workflows/shared-commit-version-and-tag.yml
    with:
      file-path: './src/BookStore.Api/BookStore.Api.csproj'
      new-version: ${{ needs.version.outputs.new-version }}
      branch: ${{ github.ref_name }}
      skip-tag: false

  deploy-to-production:
    needs: [determine-new-version, commit-version-and-tag]
    uses: ./.github/workflows/shared-deployment.yml
    with:
      webhook-url: ${{ vars.WEBHOOK_URL }}
      application-id: ${{ vars.APPLICATION_ID }}
      version: ${{ needs.version.outputs.new-version }}
      branch: ${{ github.ref_name }}