name: Master Branch Pipeline

permissions:
  contents: write

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-test:
    name: Build solution and Test
    uses: ./.github/workflows/shared-build-test.yml
    with:
      dotnet-version: '9.0.x'

  semantic-versioning:
    name: Generate New Version
    needs: [ build-and-test ]
    uses: ./.github/workflows/shared-dotnet-semantic-version.yml
    with:
      version-file-path: './src/BookStore.Api/BookStore.Api.csproj'
  
  push-to-ecr:
    name: Push Docker image to ECR
    needs: [ semantic-versioning ]
    uses: ./.github/workflows/shared-aws-ecr-push.yml
    with:
      dockerfile-path: './Dockerfile'
      aws-region: ${{ vars.AWS_REGION }}
      ecr-repository: ${{ vars.ECR_REPOSITORY_NAME }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      # deploy:
      # name: Deploy to Target Environment
      # needs: [ semantic-versioning ]
      # uses: ./.github/workflows/shared-node-deployment.yml
      # with:
      #deployment-service-address: ${{ vars.DEPLOYMENT_SERVICE_ADDRESS }}
      #application-id: ${{ vars.APPLICATION_ID }}
      #version: ${{ needs.semantic-versioning.outputs.new-version }}
      #branch: ${{ github.ref_name }}