name: Master Branch Workflow

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      - name: Send Webhook Notification
        if: success()
        run: |
          curl -X POST "${{ vars.WEBHOOK_URL }}/api/github" \
          -H "Content-Type: application/json" \
          -d '{
            "branch": "${{ github.ref_name }}",
            "appId": "${{ vars.APPLICATION_ID }}"
          }'
