name: Set next version and tag

on:
  workflow_call:
    inputs:
      file-path:
        required: true
        type: string
        description: "Path to the file to be committed"
      new-version:
        required: true
        type: string
        description: "New version to be set"
      branch:
        required: true
        type: string
        description: "Branch to commit to"

jobs:
  git-operations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update version in file
        shell: bash
        run: |
          sed -i "s|<Version>.*</Version>|<Version>${{ inputs.new-version }}</Version>|" "${{ inputs.file-path }}"

      - name: Commit version update
        run: |
          git add "${{ inputs.file-path }}"
          git commit -m "chore: bump version to ${{ inputs.new-version }} [skip ci]"
          git push origin master

      - name: Create and push tag
        run: |
          git tag -a "v${{ inputs.new-version }}" -m "Release version ${{ inputs.new-version }}"
          git push origin "v${{ inputs.new-version }}"